nats: docker-compose up
inventory_service: ./wait-for-nats.sh "python3 inventory.py"
products_service: ./wait-for-nats.sh "ruby2.0 products.rb"
price_service: ./wait-for-nats.sh "cd price && mix local.hex --force && mix run"
api_service:	./wait-for-nats.sh "cd api && go run api.go"
cart_service: cd cart && elm-reactor --address=0.0.0.0 --port=8080
